#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TESTS_DIR="$ROOT_DIR/tests"
MANIFEST="$TESTS_DIR/manifest.json"
COMPILER="${COMPILER:-$ROOT_DIR/bin/protoscriptc}"
PS="${PS:-$ROOT_DIR/c/ps}"
CLI_RUNTIME_PARITY_MODULES="${CLI_RUNTIME_PARITY_MODULES:-1}"
MODULES_BUILT=0
MODULES_TMP_DIR=""

if ! command -v jq >/dev/null 2>&1; then
  if [[ -x "/usr/local/bin/jq" ]]; then
    PATH="/usr/local/bin:$PATH"
  elif [[ -x "/opt/local/bin/jq" ]]; then
    PATH="/opt/local/bin:$PATH"
  fi
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required." >&2
  exit 2
fi

if [[ "$CLI_RUNTIME_PARITY_MODULES" == "1" ]]; then
  export PS_MODULE_REGISTRY="${PS_MODULE_REGISTRY:-$ROOT_DIR/modules/registry.json}"
  if [[ -z "${PS_MODULE_PATH:-}" ]]; then
    MODULES_TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ps_modules_cli_runtime_XXXXXX")"
    export PS_MODULE_PATH="$MODULES_TMP_DIR"
  fi
fi

cleanup_modules_tmp() {
  if [[ -n "$MODULES_TMP_DIR" && -d "$MODULES_TMP_DIR" ]]; then
    rm -rf "$MODULES_TMP_DIR"
  fi
}
trap cleanup_modules_tmp EXIT

pass=0
fail=0
skip=0

# Allowed normalization list (strict):
# - volatile temporary file tokens generated by the Node runner (ps_<uuid>_<n>)
normalize_stream() {
  local src="$1"
  local dst="$2"
  sed -E 's#([A-Za-z0-9_./-]*/)?ps_[0-9a-fA-F-]+_[0-9]+#ps_tmp#g' "$src" >"$dst"
}

echo "== CLI Runtime Parity (protoscriptc --run vs c/ps run) =="
echo "Node compiler: $COMPILER"
echo "CLI runtime:   $PS"
echo

while IFS= read -r case_id; do
  [[ -z "$case_id" ]] && continue
  src="$TESTS_DIR/$case_id.pts"
  expect="$TESTS_DIR/$case_id.expect.json"

  if [[ ! -f "$src" || ! -f "$expect" ]]; then
    echo "FAIL $case_id"
    echo "  missing source or expectation file"
    fail=$((fail + 1))
    continue
  fi

  status="$(jq -r '.status // empty' "$expect")"
  if [[ "$status" != "accept-runtime" && "$status" != "reject-runtime" ]]; then
    continue
  fi

  requires_modules="$(jq -r '.requires | index("modules") // empty' "$expect")"
  if [[ -n "$requires_modules" && "$CLI_RUNTIME_PARITY_MODULES" != "1" ]]; then
    echo "SKIP $case_id (modules not enabled)"
    skip=$((skip + 1))
    continue
  fi

  if [[ -n "$requires_modules" && "$CLI_RUNTIME_PARITY_MODULES" == "1" && "$MODULES_BUILT" == "0" ]]; then
    if [[ -x "$TESTS_DIR/build_modules.sh" ]]; then
      "$TESTS_DIR/build_modules.sh" >/tmp/ps_cli_runtime_modules_build.out 2>&1 || {
        echo "FAIL $case_id"
        echo "  failed to build test modules"
        sed -n '1,80p' /tmp/ps_cli_runtime_modules_build.out
        fail=$((fail + 1))
        continue
      }
      MODULES_BUILT=1
    else
      echo "FAIL $case_id"
      echo "  module build script missing"
      fail=$((fail + 1))
      continue
    fi
  fi

  out_node="$(mktemp)"
  err_node="$(mktemp)"
  out_cli="$(mktemp)"
  err_cli="$(mktemp)"
  out_node_norm="$(mktemp)"
  err_node_norm="$(mktemp)"
  out_cli_norm="$(mktemp)"
  err_cli_norm="$(mktemp)"

  set +e
  "$COMPILER" --run "$src" >"$out_node" 2>"$err_node"
  rc_node=$?
  "$PS" run "$src" >"$out_cli" 2>"$err_cli"
  rc_cli=$?
  set -e
  normalize_stream "$out_node" "$out_node_norm"
  normalize_stream "$err_node" "$err_node_norm"
  normalize_stream "$out_cli" "$out_cli_norm"
  normalize_stream "$err_cli" "$err_cli_norm"

  ok=true
  reason=""
  if [[ "$rc_node" -ne "$rc_cli" ]]; then
    ok=false
    reason="exit code diverges ($rc_node vs $rc_cli)"
  elif ! cmp -s "$out_node_norm" "$out_cli_norm"; then
    ok=false
    reason="stdout diverges"
  elif ! cmp -s "$err_node_norm" "$err_cli_norm"; then
    ok=false
    reason="stderr diverges"
  fi

  if [[ "$ok" == true ]]; then
    echo "PASS $case_id"
    pass=$((pass + 1))
  else
    echo "FAIL $case_id"
    echo "  $reason"
    echo "  node rc=$rc_node cli rc=$rc_cli"
    if [[ "$reason" == "stdout diverges" ]]; then
      echo "  stdout diff (normalized):"
      diff -u "$out_node_norm" "$out_cli_norm" | sed -n '1,80p' || true
    elif [[ "$reason" == "stderr diverges" ]]; then
      echo "  stderr diff (normalized):"
      diff -u "$err_node_norm" "$err_cli_norm" | sed -n '1,80p' || true
    else
      echo "  node stdout:"
      sed -n '1,40p' "$out_node"
      echo "  cli stdout:"
      sed -n '1,40p' "$out_cli"
      echo "  node stderr:"
      sed -n '1,80p' "$err_node"
      echo "  cli stderr:"
      sed -n '1,80p' "$err_cli"
    fi
    fail=$((fail + 1))
  fi

  rm -f "$out_node" "$err_node" "$out_cli" "$err_cli" "$out_node_norm" "$err_node_norm" "$out_cli_norm" "$err_cli_norm"
done < <(jq -r '.suites | to_entries[] | .value[]' "$MANIFEST")

echo
echo "Summary: PASS=$pass FAIL=$fail SKIP=$skip TOTAL=$((pass + fail + skip))"
if [[ "$fail" -ne 0 ]]; then
  exit 1
fi
echo "CLI runtime parity PASSED."
