program        = { declaration } ;
declaration    = import_decl | function_decl | prototype_decl | group_decl ;
import_decl    = "import" identifier ";" ;
function_decl  = "function" identifier "(" [ params ] ")" ":" type block ;
params         = param { "," param } ;
param          = type identifier ;
prototype_decl = [ "sealed" ] "prototype" identifier [ ":" identifier ] "{" { member } "}" ;
group_decl     = type "group" identifier "{" group_entry { "," group_entry } [ "," ] "}" ;
group_entry    = identifier "=" integer ;
member         = field_decl | method_decl ;
field_decl     = type identifier [ "=" expression ] ";" ;
method_decl    = "function" identifier "(" [ params ] ")" ":" type block ;
block          = "{" { statement } "}" ;
statement      = block | if_stmt | while_stmt | for_stmt | return_stmt | var_decl | expr_stmt ;
if_stmt        = "if" "(" expression ")" statement [ "else" statement ] ;
while_stmt     = "while" "(" expression ")" statement ;
for_stmt       = "for" "(" [ statement ] [ expression ] ";" [ expression ] ")" statement ;
return_stmt    = "return" [ expression ] ";" ;
var_decl       = [ "const" ] type identifier [ "=" expression ] ";" ;
expr_stmt      = expression ";" ;
expression     = assignment ;
assignment     = logic_or [ "=" assignment ] ;
logic_or       = logic_and { "||" logic_and } ;
logic_and      = equality { "&&" equality } ;
equality       = relation { ( "==" | "!=" ) relation } ;
relation       = add { ( "<" | "<=" | ">" | ">=" ) add } ;
add            = mul { ( "+" | "-" ) mul } ;
mul            = unary { ( "*" | "/" | "%" ) unary } ;
unary          = [ "!" | "-" ] primary ;
primary        = integer | float | string | "true" | "false" | identifier | "(" expression ")" ;
type           = "int" | "float" | "bool" | "byte" | "glyph" | "string" | "void" | identifier ;
identifier     = letter { letter | digit | "_" } ;
integer        = digit { digit } ;
float          = integer "." integer ;
string         = "\"" { ? any char except quote/newline ? } "\"" ;
letter         = "A"…"Z" | "a"…"z" ;
digit          = "0"…"9" ;
